<?xml version="1.0" encoding="utf-8"?><Database Name="StatisticsReportForReferenceServices" Class="StatisticsReportForReferenceServicesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=sql-clus;Initial Catalog=StatisticsReportForReferenceServices;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="StatisticsReportForReferenceServicesConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.GetAllDepartments" Method="GetAllDepartments">
    <ElementType Name="GetAllDepartmentsResult">
      <Column Name="Department_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Department_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Department_Domain" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UsersSearch" Method="UsersSearch">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="UsersSearchResult">
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="User_Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Is_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllUsers" Method="GetAllUsers">
    <ElementType Name="GetAllUsersResult">
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="User_Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Is_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRealDepartments" Method="GetRealDepartments">
    <ElementType Name="GetRealDepartmentsResult">
      <Column Name="Department_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Department_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Department_Domain" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetRoleByUserID" Method="GetRoleByUserID">
    <Parameter Name="USER_ID" Parameter="uSER_ID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetRoleByUserIDResult">
      <Column Name="User_Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Is_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.getVistorByID" Method="getVistorByID">
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.String" DbType="VarChar(255)" />
    <ElementType Name="getVistorByIDResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NationalID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.IsValidUser" Method="IsValidUser">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="IsValidUserResult">
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="User_Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="User_Is_Locked" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ItemsSearch" Method="ItemsSearch">
    <Parameter Name="Number" Parameter="number" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Customer_Name" Parameter="customer_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Customer_Gender" Parameter="customer_Gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Finsh_date" Parameter="finsh_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Period" Parameter="period" Type="System.Int32" DbType="Int" />
    <Parameter Name="Send_Method" Parameter="send_Method" Type="System.Int32" DbType="Int" />
    <Parameter Name="Language" Parameter="language" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search_Type" Parameter="search_Type" Type="System.Int32" DbType="Int" />
    <Parameter Name="Creation_Date" Parameter="creation_Date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IsBook" Parameter="isBook" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsArticle" Parameter="isArticle" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsThesis" Parameter="isThesis" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsDocument" Parameter="isDocument" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsImage" Parameter="isImage" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsManuscript" Parameter="isManuscript" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumOfItems" Parameter="numOfItems" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumOfPages" Parameter="numOfPages" Type="System.Int32" DbType="Int" />
    <ElementType Name="ItemsSearchResult">
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Finsh_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Send_Method" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Search_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Degree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsBook" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsArticle" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsThesis" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDocument" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsImage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsManuscript" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NumOfItems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumOfPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ItemsSearchWithUsers" Method="ItemsSearchWithUsers">
    <Parameter Name="Number" Parameter="number" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Customer_Name" Parameter="customer_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Customer_Gender" Parameter="customer_Gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Finsh_date" Parameter="finsh_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Period" Parameter="period" Type="System.Int32" DbType="Int" />
    <Parameter Name="Send_Method" Parameter="send_Method" Type="System.Int32" DbType="Int" />
    <Parameter Name="Language" Parameter="language" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DepartmentID" Parameter="departmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Creation_Date" Parameter="creation_Date" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IsBook" Parameter="isBook" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsArticle" Parameter="isArticle" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsThesis" Parameter="isThesis" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsDocument" Parameter="isDocument" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsImage" Parameter="isImage" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsManuscript" Parameter="isManuscript" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumOfItems" Parameter="numOfItems" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumOfPages" Parameter="numOfPages" Type="System.Int32" DbType="Int" />
    <ElementType Name="ItemsSearchWithUsersResult">
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="User_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Customer_Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Customer_Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Finsh_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Send_Method" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Degree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Department_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsBook" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsArticle" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsThesis" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDocument" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsImage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsManuscript" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NumOfItems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumOfPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LogErrorAdd" Method="LogErrorAdd">
    <Parameter Name="Message" Parameter="message" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="SatckTrace" Parameter="satckTrace" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.StatisticsSearch" Method="StatisticsSearch">
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Finsh_date" Parameter="finsh_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="DepartmentId" Parameter="departmentId" Type="System.Int32" DbType="Int" />
    <ElementType Name="StatisticsSearchResult">
      <Column Name="Customer_Gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Period" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Send_Method" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Language" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Search_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Degree" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsBook" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsArticle" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsThesis" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDocument" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsImage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsManuscript" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NumOfItems" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumOfPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.User_Is_LockedEdit" Method="User_Is_LockedEdit">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UsersAdd" Method="UsersAdd">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="User_Name" Parameter="user_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="User_Role" Parameter="user_Role" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DepartmentID" Parameter="departmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UsersDelete" Method="UsersDelete">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UsersEdit" Method="UsersEdit">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="User_Name" Parameter="user_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="User_Role" Parameter="user_Role" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DepartmentID" Parameter="departmentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ItemsAdd" Method="ItemsAdd">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Customer_Name" Parameter="customer_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Customer_Gender" Parameter="customer_Gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Finsh_date" Parameter="finsh_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Period" Parameter="period" Type="System.Int32" DbType="Int" />
    <Parameter Name="Send_Method" Parameter="send_Method" Type="System.Int32" DbType="Int" />
    <Parameter Name="Language" Parameter="language" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search_Type" Parameter="search_Type" Type="System.Int32" DbType="Int" />
    <Parameter Name="Degree" Parameter="degree" Type="System.Int32" DbType="Int" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IsBook" Parameter="isBook" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsArticle" Parameter="isArticle" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsThesis" Parameter="isThesis" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsDocument" Parameter="isDocument" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsImage" Parameter="isImage" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsManuscript" Parameter="isManuscript" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumOfItems" Parameter="numOfItems" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumOfPages" Parameter="numOfPages" Type="System.Int32" DbType="Int" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="Number" Parameter="number" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ItemsEdit" Method="ItemsEdit">
    <Parameter Name="Number" Parameter="number" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Customer_Name" Parameter="customer_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Customer_Gender" Parameter="customer_Gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Finsh_date" Parameter="finsh_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Period" Parameter="period" Type="System.Int32" DbType="Int" />
    <Parameter Name="Send_Method" Parameter="send_Method" Type="System.Int32" DbType="Int" />
    <Parameter Name="Language" Parameter="language" Type="System.Int32" DbType="Int" />
    <Parameter Name="Search_Type" Parameter="search_Type" Type="System.Int32" DbType="Int" />
    <Parameter Name="Degree" Parameter="degree" Type="System.Int32" DbType="Int" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IsBook" Parameter="isBook" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsArticle" Parameter="isArticle" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsThesis" Parameter="isThesis" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsDocument" Parameter="isDocument" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsImage" Parameter="isImage" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IsManuscript" Parameter="isManuscript" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumOfItems" Parameter="numOfItems" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumOfPages" Parameter="numOfPages" Type="System.Int32" DbType="Int" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GeneralCollectionAdd" Method="GeneralCollectionAdd">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_Name" Parameter="vistor_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Counter_ID" Parameter="counter_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NoBooks" Parameter="noBooks" Type="System.Int32" DbType="Int" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="GeneralCollectionAddResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vistor_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Counter_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoBooks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GeneralCollectionSearch" Method="GeneralCollectionSearch">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_Name" Parameter="vistor_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Counter_ID" Parameter="counter_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GeneralCollectionSearchResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vistor_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Counter_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoBooks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GeneralCollectionDelete" Method="GeneralCollectionDelete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GeneralCollectionEdit" Method="GeneralCollectionEdit">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_Name" Parameter="vistor_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Counter_ID" Parameter="counter_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NoBooks" Parameter="noBooks" Type="System.Int32" DbType="Int" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="GeneralCollectionEditResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vistor_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Counter_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoBooks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GeneralCollectionSearchWithUsers" Method="GeneralCollectionSearchWithUsers">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_Name" Parameter="vistor_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Counter_ID" Parameter="counter_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GeneralCollectionSearchWithUsersResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vistor_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Counter_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoBooks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PhotocopySearch" Method="PhotocopySearch">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_Name" Parameter="vistor_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="PhotocopySearchResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vistor_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NoPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoBooks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PhotocopyAdd" Method="PhotocopyAdd">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_Name" Parameter="vistor_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="NoPages" Parameter="noPages" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NoBooks" Parameter="noBooks" Type="System.Int32" DbType="Int" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="PhotocopyAddResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vistor_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NoPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoBooks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PhotocopyDelete" Method="PhotocopyDelete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PhotocopyEdit" Method="PhotocopyEdit">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_Name" Parameter="vistor_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="NoPages" Parameter="noPages" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NoBooks" Parameter="noBooks" Type="System.Int32" DbType="Int" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="PhotocopyEditResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vistor_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NoPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoBooks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PhotocopySearchWithUsers" Method="PhotocopySearchWithUsers">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Vistor_ID" Parameter="vistor_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Vistor_Name" Parameter="vistor_Name" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Int32" DbType="Int" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MobileNo" Parameter="mobileNo" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="PhotocopySearchWithUsersResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Vistor_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vistor_Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NoPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoBooks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BooksReceivedSerachWithusers" Method="BooksReceivedSerachWithusers">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="BooksReceivedSerachWithusersResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoCopy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoTitle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BooksReceivedAdd" Method="BooksReceivedAdd">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NoCopy" Parameter="noCopy" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoTitle" Parameter="noTitle" Type="System.Int32" DbType="Int" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="BooksReceivedAddResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoCopy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoTitle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BooksReceivedDelete" Method="BooksReceivedDelete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BooksReceivedEdit" Method="BooksReceivedEdit">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NoCopy" Parameter="noCopy" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoTitle" Parameter="noTitle" Type="System.Int32" DbType="Int" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="BooksReceivedEditResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoCopy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoTitle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BooksReceivedSerach" Method="BooksReceivedSerach">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="BooksReceivedSerachResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoCopy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoTitle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SortingAndOrgnizeAdd" Method="SortingAndOrgnizeAdd">
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NoReindex" Parameter="noReindex" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoRelabel" Parameter="noRelabel" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoBinding" Parameter="noBinding" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoExclude" Parameter="noExclude" Type="System.Int32" DbType="Int" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SortingAndOrgnizeAddResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoReindex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoRelabel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoBinding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoExclude" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SortingAndOrgnizeSearchWithUsers" Method="SortingAndOrgnizeSearchWithUsers">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="SortingAndOrgnizeSearchWithUsersResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoReindex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoRelabel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoBinding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoExclude" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SortingAndOrgnizeDelete" Method="SortingAndOrgnizeDelete">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SortingAndOrgnizeEdit" Method="SortingAndOrgnizeEdit">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="NoReindex" Parameter="noReindex" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoRelabel" Parameter="noRelabel" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoBinding" Parameter="noBinding" Type="System.Int32" DbType="Int" />
    <Parameter Name="NoExclude" Parameter="noExclude" Type="System.Int32" DbType="Int" />
    <Parameter Name="Result" Parameter="result" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType Name="SortingAndOrgnizeEditResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoReindex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoRelabel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoBinding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoExclude" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SortingAndOrgnizeSearch" Method="SortingAndOrgnizeSearch">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="User_ID" Parameter="user_ID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Receive_Date" Parameter="receive_Date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="SortingAndOrgnizeSearchResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="User_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Receive_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoReindex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoRelabel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoBinding" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoExclude" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Creation_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>