#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StatisticsReportForReferenceServices")]
public partial class StatisticsReportForReferenceServicesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public StatisticsReportForReferenceServicesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["StatisticsReportForReferenceServicesConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public StatisticsReportForReferenceServicesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StatisticsReportForReferenceServicesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StatisticsReportForReferenceServicesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public StatisticsReportForReferenceServicesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllDepartments")]
	public ISingleResult<GetAllDepartmentsResult> GetAllDepartments()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetAllDepartmentsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersSearch")]
	public ISingleResult<UsersSearchResult> UsersSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID);
		return ((ISingleResult<UsersSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAllUsers")]
	public ISingleResult<GetAllUsersResult> GetAllUsers()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetAllUsersResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRealDepartments")]
	public ISingleResult<GetRealDepartmentsResult> GetRealDepartments()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetRealDepartmentsResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRoleByUserID")]
	public ISingleResult<GetRoleByUserIDResult> GetRoleByUserID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="NVarChar(50)")] string uSER_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_ID);
		return ((ISingleResult<GetRoleByUserIDResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getVistorByID")]
	public ISingleResult<getVistorByIDResult> getVistorByID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_ID", DbType="VarChar(255)")] string vistor_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), vistor_ID);
		return ((ISingleResult<getVistorByIDResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsValidUser")]
	public ISingleResult<IsValidUserResult> IsValidUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID);
		return ((ISingleResult<IsValidUserResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ItemsSearch")]
	public ISingleResult<ItemsSearchResult> ItemsSearch(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="Int")] System.Nullable<int> number, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_Name", DbType="NVarChar(255)")] string customer_Name, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_Gender", DbType="Int")] System.Nullable<int> customer_Gender, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Finsh_date", DbType="DateTime")] System.Nullable<System.DateTime> finsh_date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Period", DbType="Int")] System.Nullable<int> period, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Send_Method", DbType="Int")] System.Nullable<int> send_Method, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Language", DbType="Int")] System.Nullable<int> language, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search_Type", DbType="Int")] System.Nullable<int> search_Type, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Creation_Date", DbType="Date")] System.Nullable<System.DateTime> creation_Date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBook", DbType="Bit")] System.Nullable<bool> isBook, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsArticle", DbType="Bit")] System.Nullable<bool> isArticle, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsThesis", DbType="Bit")] System.Nullable<bool> isThesis, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDocument", DbType="Bit")] System.Nullable<bool> isDocument, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsImage", DbType="Bit")] System.Nullable<bool> isImage, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsManuscript", DbType="Bit")] System.Nullable<bool> isManuscript, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOfItems", DbType="Int")] System.Nullable<int> numOfItems, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOfPages", DbType="Int")] System.Nullable<int> numOfPages)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), number, user_ID, customer_Name, customer_Gender, receive_Date, finsh_date, period, send_Method, language, search_Type, creation_Date, isBook, isArticle, isThesis, isDocument, isImage, isManuscript, numOfItems, numOfPages);
		return ((ISingleResult<ItemsSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ItemsSearchWithUsers")]
	public ISingleResult<ItemsSearchWithUsersResult> ItemsSearchWithUsers(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="Int")] System.Nullable<int> number, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_Name", DbType="NVarChar(255)")] string customer_Name, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_Gender", DbType="Int")] System.Nullable<int> customer_Gender, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Finsh_date", DbType="DateTime")] System.Nullable<System.DateTime> finsh_date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Period", DbType="Int")] System.Nullable<int> period, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Send_Method", DbType="Int")] System.Nullable<int> send_Method, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Language", DbType="Int")] System.Nullable<int> language, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DepartmentID", DbType="Int")] System.Nullable<int> departmentID, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Creation_Date", DbType="NVarChar(50)")] string creation_Date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBook", DbType="Bit")] System.Nullable<bool> isBook, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsArticle", DbType="Bit")] System.Nullable<bool> isArticle, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsThesis", DbType="Bit")] System.Nullable<bool> isThesis, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDocument", DbType="Bit")] System.Nullable<bool> isDocument, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsImage", DbType="Bit")] System.Nullable<bool> isImage, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsManuscript", DbType="Bit")] System.Nullable<bool> isManuscript, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOfItems", DbType="Int")] System.Nullable<int> numOfItems, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOfPages", DbType="Int")] System.Nullable<int> numOfPages)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), number, user_ID, customer_Name, customer_Gender, receive_Date, finsh_date, period, send_Method, language, userName, departmentID, creation_Date, isBook, isArticle, isThesis, isDocument, isImage, isManuscript, numOfItems, numOfPages);
		return ((ISingleResult<ItemsSearchWithUsersResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LogErrorAdd")]
	public int LogErrorAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(MAX)")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SatckTrace", DbType="NVarChar(MAX)")] string satckTrace)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), message, satckTrace);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.StatisticsSearch")]
	public ISingleResult<StatisticsSearchResult> StatisticsSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Finsh_date", DbType="DateTime")] System.Nullable<System.DateTime> finsh_date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Int")] System.Nullable<int> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DepartmentId", DbType="Int")] System.Nullable<int> departmentId)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), receive_Date, finsh_date, userName, gender, departmentId);
		return ((ISingleResult<StatisticsSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.User_Is_LockedEdit")]
	public int User_Is_LockedEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersAdd")]
	public int UsersAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Name", DbType="NVarChar(255)")] string user_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Role", DbType="NVarChar(50)")] string user_Role, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DepartmentID", DbType="Int")] System.Nullable<int> departmentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, user_Name, user_Role, departmentID, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(4)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersDelete")]
	public int UsersDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UsersEdit")]
	public int UsersEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Name", DbType="NVarChar(255)")] string user_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_Role", DbType="NVarChar(50)")] string user_Role, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DepartmentID", DbType="Int")] System.Nullable<int> departmentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, user_Name, user_Role, departmentID, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(4)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ItemsAdd")]
	public int ItemsAdd(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_ID", DbType="Int")] System.Nullable<int> vistor_ID, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_Name", DbType="NVarChar(255)")] string customer_Name, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_Gender", DbType="Int")] System.Nullable<int> customer_Gender, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Finsh_date", DbType="DateTime")] System.Nullable<System.DateTime> finsh_date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Period", DbType="Int")] System.Nullable<int> period, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Send_Method", DbType="Int")] System.Nullable<int> send_Method, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Language", DbType="Int")] System.Nullable<int> language, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search_Type", DbType="Int")] System.Nullable<int> search_Type, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Degree", DbType="Int")] System.Nullable<int> degree, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(50)")] string mobile, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBook", DbType="Bit")] System.Nullable<bool> isBook, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsArticle", DbType="Bit")] System.Nullable<bool> isArticle, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsThesis", DbType="Bit")] System.Nullable<bool> isThesis, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDocument", DbType="Bit")] System.Nullable<bool> isDocument, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsImage", DbType="Bit")] System.Nullable<bool> isImage, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsManuscript", DbType="Bit")] System.Nullable<bool> isManuscript, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOfItems", DbType="Int")] System.Nullable<int> numOfItems, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOfPages", DbType="Int")] System.Nullable<int> numOfPages, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="Int")] ref System.Nullable<int> number)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, vistor_ID, customer_Name, customer_Gender, receive_Date, finsh_date, period, send_Method, language, search_Type, degree, mobile, isBook, isArticle, isThesis, isDocument, isImage, isManuscript, numOfItems, numOfPages, result, number);
		result = ((System.Nullable<int>)(result1.GetParameterValue(20)));
		number = ((System.Nullable<int>)(result1.GetParameterValue(21)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ItemsEdit")]
	public int ItemsEdit(
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Number", DbType="Int")] System.Nullable<int> number, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_ID", DbType="Int")] System.Nullable<int> vistor_ID, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_Name", DbType="NVarChar(255)")] string customer_Name, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Customer_Gender", DbType="Int")] System.Nullable<int> customer_Gender, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Finsh_date", DbType="DateTime")] System.Nullable<System.DateTime> finsh_date, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Period", DbType="Int")] System.Nullable<int> period, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Send_Method", DbType="Int")] System.Nullable<int> send_Method, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Language", DbType="Int")] System.Nullable<int> language, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search_Type", DbType="Int")] System.Nullable<int> search_Type, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Degree", DbType="Int")] System.Nullable<int> degree, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="NVarChar(50)")] string mobile, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBook", DbType="Bit")] System.Nullable<bool> isBook, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsArticle", DbType="Bit")] System.Nullable<bool> isArticle, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsThesis", DbType="Bit")] System.Nullable<bool> isThesis, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsDocument", DbType="Bit")] System.Nullable<bool> isDocument, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsImage", DbType="Bit")] System.Nullable<bool> isImage, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsManuscript", DbType="Bit")] System.Nullable<bool> isManuscript, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOfItems", DbType="Int")] System.Nullable<int> numOfItems, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOfPages", DbType="Int")] System.Nullable<int> numOfPages, 
				[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), number, vistor_ID, customer_Name, customer_Gender, receive_Date, finsh_date, period, send_Method, language, search_Type, degree, mobile, isBook, isArticle, isThesis, isDocument, isImage, isManuscript, numOfItems, numOfPages, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(20)));
		return ((int)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GeneralCollectionAdd")]
	public ISingleResult<GeneralCollectionAddResult> GeneralCollectionAdd([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_ID", DbType="Int")] System.Nullable<int> vistor_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_Name", DbType="NVarChar(255)")] string vistor_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Int")] System.Nullable<int> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Counter_ID", DbType="Int")] System.Nullable<int> counter_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoBooks", DbType="Int")] System.Nullable<int> noBooks, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNo", DbType="NVarChar(50)")] string mobileNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, vistor_ID, vistor_Name, gender, counter_ID, receive_Date, noBooks, mobileNo, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(8)));
		return ((ISingleResult<GeneralCollectionAddResult>)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GeneralCollectionSearch")]
	public ISingleResult<GeneralCollectionSearchResult> GeneralCollectionSearch([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_ID", DbType="Int")] System.Nullable<int> vistor_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_Name", DbType="NVarChar(255)")] string vistor_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Int")] System.Nullable<int> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Counter_ID", DbType="Int")] System.Nullable<int> counter_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNo", DbType="NVarChar(50)")] string mobileNo)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, user_ID, vistor_ID, vistor_Name, gender, counter_ID, receive_Date, mobileNo);
		return ((ISingleResult<GeneralCollectionSearchResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GeneralCollectionDelete")]
	public int GeneralCollectionDelete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GeneralCollectionEdit")]
	public ISingleResult<GeneralCollectionEditResult> GeneralCollectionEdit([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_ID", DbType="Int")] System.Nullable<int> vistor_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_Name", DbType="NVarChar(255)")] string vistor_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Int")] System.Nullable<int> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Counter_ID", DbType="Int")] System.Nullable<int> counter_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoBooks", DbType="Int")] System.Nullable<int> noBooks, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNo", DbType="NVarChar(50)")] string mobileNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Result", DbType="Int")] ref System.Nullable<int> result)
	{
		IExecuteResult result1 = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, user_ID, vistor_ID, vistor_Name, gender, counter_ID, receive_Date, noBooks, mobileNo, result);
		result = ((System.Nullable<int>)(result1.GetParameterValue(9)));
		return ((ISingleResult<GeneralCollectionEditResult>)(result1.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GeneralCollectionSearchWithUsers")]
	public ISingleResult<GeneralCollectionSearchWithUsersResult> GeneralCollectionSearchWithUsers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_ID", DbType="Int")] System.Nullable<int> vistor_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Vistor_Name", DbType="NVarChar(255)")] string vistor_Name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Int")] System.Nullable<int> gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Counter_ID", DbType="Int")] System.Nullable<int> counter_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Receive_Date", DbType="DateTime")] System.Nullable<System.DateTime> receive_Date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MobileNo", DbType="NVarChar(50)")] string mobileNo)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, user_ID, vistor_ID, vistor_Name, gender, counter_ID, receive_Date, mobileNo);
		return ((ISingleResult<GeneralCollectionSearchWithUsersResult>)(result.ReturnValue));
	}
}

public partial class GetAllDepartmentsResult
{
	
	private int _Department_id;
	
	private string _Department_Name;
	
	private string _Department_Domain;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	public GetAllDepartmentsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_id", DbType="Int NOT NULL")]
	public int Department_id
	{
		get
		{
			return this._Department_id;
		}
		set
		{
			if ((this._Department_id != value))
			{
				this._Department_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Department_Name
	{
		get
		{
			return this._Department_Name;
		}
		set
		{
			if ((this._Department_Name != value))
			{
				this._Department_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Domain", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Department_Domain
	{
		get
		{
			return this._Department_Domain;
		}
		set
		{
			if ((this._Department_Domain != value))
			{
				this._Department_Domain = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
}

public partial class UsersSearchResult
{
	
	private string _User_ID;
	
	private string _User_Name;
	
	private string _User_Role;
	
	private bool _User_Is_Locked;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	private System.Nullable<int> _DepartmentID;
	
	public UsersSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(255)")]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this._User_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Role", DbType="NVarChar(50)")]
	public string User_Role
	{
		get
		{
			return this._User_Role;
		}
		set
		{
			if ((this._User_Role != value))
			{
				this._User_Role = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Is_Locked", DbType="Bit NOT NULL")]
	public bool User_Is_Locked
	{
		get
		{
			return this._User_Is_Locked;
		}
		set
		{
			if ((this._User_Is_Locked != value))
			{
				this._User_Is_Locked = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentID", DbType="Int")]
	public System.Nullable<int> DepartmentID
	{
		get
		{
			return this._DepartmentID;
		}
		set
		{
			if ((this._DepartmentID != value))
			{
				this._DepartmentID = value;
			}
		}
	}
}

public partial class GetAllUsersResult
{
	
	private string _User_ID;
	
	private string _User_Name;
	
	private string _User_Role;
	
	private bool _User_Is_Locked;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	public GetAllUsersResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(255)")]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this._User_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Role", DbType="NVarChar(50)")]
	public string User_Role
	{
		get
		{
			return this._User_Role;
		}
		set
		{
			if ((this._User_Role != value))
			{
				this._User_Role = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Is_Locked", DbType="Bit NOT NULL")]
	public bool User_Is_Locked
	{
		get
		{
			return this._User_Is_Locked;
		}
		set
		{
			if ((this._User_Is_Locked != value))
			{
				this._User_Is_Locked = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
}

public partial class GetRealDepartmentsResult
{
	
	private int _Department_id;
	
	private string _Department_Name;
	
	private string _Department_Domain;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	public GetRealDepartmentsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_id", DbType="Int NOT NULL")]
	public int Department_id
	{
		get
		{
			return this._Department_id;
		}
		set
		{
			if ((this._Department_id != value))
			{
				this._Department_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Department_Name
	{
		get
		{
			return this._Department_Name;
		}
		set
		{
			if ((this._Department_Name != value))
			{
				this._Department_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Domain", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Department_Domain
	{
		get
		{
			return this._Department_Domain;
		}
		set
		{
			if ((this._Department_Domain != value))
			{
				this._Department_Domain = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
}

public partial class GetRoleByUserIDResult
{
	
	private string _User_Role;
	
	private bool _User_Is_Locked;
	
	public GetRoleByUserIDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Role", DbType="NVarChar(50)")]
	public string User_Role
	{
		get
		{
			return this._User_Role;
		}
		set
		{
			if ((this._User_Role != value))
			{
				this._User_Role = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Is_Locked", DbType="Bit NOT NULL")]
	public bool User_Is_Locked
	{
		get
		{
			return this._User_Is_Locked;
		}
		set
		{
			if ((this._User_Is_Locked != value))
			{
				this._User_Is_Locked = value;
			}
		}
	}
}

public partial class getVistorByIDResult
{
	
	private int _ID;
	
	private string _Name;
	
	private bool _Gender;
	
	private string _Mobile;
	
	private string _NationalID;
	
	public getVistorByIDResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Bit NOT NULL")]
	public bool Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
	public string Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this._Mobile = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NationalID", DbType="NVarChar(50)")]
	public string NationalID
	{
		get
		{
			return this._NationalID;
		}
		set
		{
			if ((this._NationalID != value))
			{
				this._NationalID = value;
			}
		}
	}
}

public partial class IsValidUserResult
{
	
	private string _User_ID;
	
	private string _User_Name;
	
	private string _User_Role;
	
	private bool _User_Is_Locked;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	public IsValidUserResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(255)")]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this._User_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Role", DbType="NVarChar(50)")]
	public string User_Role
	{
		get
		{
			return this._User_Role;
		}
		set
		{
			if ((this._User_Role != value))
			{
				this._User_Role = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Is_Locked", DbType="Bit NOT NULL")]
	public bool User_Is_Locked
	{
		get
		{
			return this._User_Is_Locked;
		}
		set
		{
			if ((this._User_Is_Locked != value))
			{
				this._User_Is_Locked = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
}

public partial class ItemsSearchResult
{
	
	private int _Number;
	
	private string _User_ID;
	
	private string _Customer_Name;
	
	private int _Customer_Gender;
	
	private System.Nullable<System.DateTime> _Receive_Date;
	
	private System.Nullable<System.DateTime> _Finsh_date;
	
	private int _Period;
	
	private int _Send_Method;
	
	private int _Language;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	private int _Search_Type;
	
	private string _Mobile;
	
	private int _Degree;
	
	private System.Nullable<int> _Vistor_ID;
	
	private bool _IsBook;
	
	private bool _IsArticle;
	
	private bool _IsThesis;
	
	private bool _IsDocument;
	
	private bool _IsImage;
	
	private bool _IsManuscript;
	
	private System.Nullable<int> _NumOfItems;
	
	private System.Nullable<int> _NumOfPages;
	
	public ItemsSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
	public int Number
	{
		get
		{
			return this._Number;
		}
		set
		{
			if ((this._Number != value))
			{
				this._Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string Customer_Name
	{
		get
		{
			return this._Customer_Name;
		}
		set
		{
			if ((this._Customer_Name != value))
			{
				this._Customer_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Gender", DbType="Int NOT NULL")]
	public int Customer_Gender
	{
		get
		{
			return this._Customer_Gender;
		}
		set
		{
			if ((this._Customer_Gender != value))
			{
				this._Customer_Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receive_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Receive_Date
	{
		get
		{
			return this._Receive_Date;
		}
		set
		{
			if ((this._Receive_Date != value))
			{
				this._Receive_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finsh_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Finsh_date
	{
		get
		{
			return this._Finsh_date;
		}
		set
		{
			if ((this._Finsh_date != value))
			{
				this._Finsh_date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="Int NOT NULL")]
	public int Period
	{
		get
		{
			return this._Period;
		}
		set
		{
			if ((this._Period != value))
			{
				this._Period = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Send_Method", DbType="Int NOT NULL")]
	public int Send_Method
	{
		get
		{
			return this._Send_Method;
		}
		set
		{
			if ((this._Send_Method != value))
			{
				this._Send_Method = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="Int NOT NULL")]
	public int Language
	{
		get
		{
			return this._Language;
		}
		set
		{
			if ((this._Language != value))
			{
				this._Language = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Search_Type", DbType="Int NOT NULL")]
	public int Search_Type
	{
		get
		{
			return this._Search_Type;
		}
		set
		{
			if ((this._Search_Type != value))
			{
				this._Search_Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
	public string Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this._Mobile = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degree", DbType="Int NOT NULL")]
	public int Degree
	{
		get
		{
			return this._Degree;
		}
		set
		{
			if ((this._Degree != value))
			{
				this._Degree = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_ID", DbType="Int")]
	public System.Nullable<int> Vistor_ID
	{
		get
		{
			return this._Vistor_ID;
		}
		set
		{
			if ((this._Vistor_ID != value))
			{
				this._Vistor_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBook", DbType="Bit NOT NULL")]
	public bool IsBook
	{
		get
		{
			return this._IsBook;
		}
		set
		{
			if ((this._IsBook != value))
			{
				this._IsBook = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsArticle", DbType="Bit NOT NULL")]
	public bool IsArticle
	{
		get
		{
			return this._IsArticle;
		}
		set
		{
			if ((this._IsArticle != value))
			{
				this._IsArticle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsThesis", DbType="Bit NOT NULL")]
	public bool IsThesis
	{
		get
		{
			return this._IsThesis;
		}
		set
		{
			if ((this._IsThesis != value))
			{
				this._IsThesis = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDocument", DbType="Bit NOT NULL")]
	public bool IsDocument
	{
		get
		{
			return this._IsDocument;
		}
		set
		{
			if ((this._IsDocument != value))
			{
				this._IsDocument = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsImage", DbType="Bit NOT NULL")]
	public bool IsImage
	{
		get
		{
			return this._IsImage;
		}
		set
		{
			if ((this._IsImage != value))
			{
				this._IsImage = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsManuscript", DbType="Bit NOT NULL")]
	public bool IsManuscript
	{
		get
		{
			return this._IsManuscript;
		}
		set
		{
			if ((this._IsManuscript != value))
			{
				this._IsManuscript = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOfItems", DbType="Int")]
	public System.Nullable<int> NumOfItems
	{
		get
		{
			return this._NumOfItems;
		}
		set
		{
			if ((this._NumOfItems != value))
			{
				this._NumOfItems = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOfPages", DbType="Int")]
	public System.Nullable<int> NumOfPages
	{
		get
		{
			return this._NumOfPages;
		}
		set
		{
			if ((this._NumOfPages != value))
			{
				this._NumOfPages = value;
			}
		}
	}
}

public partial class ItemsSearchWithUsersResult
{
	
	private int _Number;
	
	private string _User_ID;
	
	private string _User_Name;
	
	private string _Customer_Name;
	
	private int _Customer_Gender;
	
	private System.Nullable<System.DateTime> _Receive_Date;
	
	private System.Nullable<System.DateTime> _Finsh_date;
	
	private int _Period;
	
	private int _Send_Method;
	
	private int _Language;
	
	private int _Search_Type;
	
	private string _Mobile;
	
	private int _Degree;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	private string _Department_Name;
	
	private System.Nullable<int> _Vistor_ID;
	
	private bool _IsBook;
	
	private bool _IsArticle;
	
	private bool _IsThesis;
	
	private bool _IsDocument;
	
	private bool _IsImage;
	
	private bool _IsManuscript;
	
	private System.Nullable<int> _NumOfItems;
	
	private System.Nullable<int> _NumOfPages;
	
	public ItemsSearchWithUsersResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int NOT NULL")]
	public int Number
	{
		get
		{
			return this._Number;
		}
		set
		{
			if ((this._Number != value))
			{
				this._Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(255)")]
	public string User_Name
	{
		get
		{
			return this._User_Name;
		}
		set
		{
			if ((this._User_Name != value))
			{
				this._User_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string Customer_Name
	{
		get
		{
			return this._Customer_Name;
		}
		set
		{
			if ((this._Customer_Name != value))
			{
				this._Customer_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Gender", DbType="Int NOT NULL")]
	public int Customer_Gender
	{
		get
		{
			return this._Customer_Gender;
		}
		set
		{
			if ((this._Customer_Gender != value))
			{
				this._Customer_Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receive_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Receive_Date
	{
		get
		{
			return this._Receive_Date;
		}
		set
		{
			if ((this._Receive_Date != value))
			{
				this._Receive_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finsh_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Finsh_date
	{
		get
		{
			return this._Finsh_date;
		}
		set
		{
			if ((this._Finsh_date != value))
			{
				this._Finsh_date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="Int NOT NULL")]
	public int Period
	{
		get
		{
			return this._Period;
		}
		set
		{
			if ((this._Period != value))
			{
				this._Period = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Send_Method", DbType="Int NOT NULL")]
	public int Send_Method
	{
		get
		{
			return this._Send_Method;
		}
		set
		{
			if ((this._Send_Method != value))
			{
				this._Send_Method = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="Int NOT NULL")]
	public int Language
	{
		get
		{
			return this._Language;
		}
		set
		{
			if ((this._Language != value))
			{
				this._Language = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Search_Type", DbType="Int NOT NULL")]
	public int Search_Type
	{
		get
		{
			return this._Search_Type;
		}
		set
		{
			if ((this._Search_Type != value))
			{
				this._Search_Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="NVarChar(50)")]
	public string Mobile
	{
		get
		{
			return this._Mobile;
		}
		set
		{
			if ((this._Mobile != value))
			{
				this._Mobile = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degree", DbType="Int NOT NULL")]
	public int Degree
	{
		get
		{
			return this._Degree;
		}
		set
		{
			if ((this._Degree != value))
			{
				this._Degree = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Department_Name
	{
		get
		{
			return this._Department_Name;
		}
		set
		{
			if ((this._Department_Name != value))
			{
				this._Department_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_ID", DbType="Int")]
	public System.Nullable<int> Vistor_ID
	{
		get
		{
			return this._Vistor_ID;
		}
		set
		{
			if ((this._Vistor_ID != value))
			{
				this._Vistor_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBook", DbType="Bit NOT NULL")]
	public bool IsBook
	{
		get
		{
			return this._IsBook;
		}
		set
		{
			if ((this._IsBook != value))
			{
				this._IsBook = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsArticle", DbType="Bit NOT NULL")]
	public bool IsArticle
	{
		get
		{
			return this._IsArticle;
		}
		set
		{
			if ((this._IsArticle != value))
			{
				this._IsArticle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsThesis", DbType="Bit NOT NULL")]
	public bool IsThesis
	{
		get
		{
			return this._IsThesis;
		}
		set
		{
			if ((this._IsThesis != value))
			{
				this._IsThesis = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDocument", DbType="Bit NOT NULL")]
	public bool IsDocument
	{
		get
		{
			return this._IsDocument;
		}
		set
		{
			if ((this._IsDocument != value))
			{
				this._IsDocument = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsImage", DbType="Bit NOT NULL")]
	public bool IsImage
	{
		get
		{
			return this._IsImage;
		}
		set
		{
			if ((this._IsImage != value))
			{
				this._IsImage = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsManuscript", DbType="Bit NOT NULL")]
	public bool IsManuscript
	{
		get
		{
			return this._IsManuscript;
		}
		set
		{
			if ((this._IsManuscript != value))
			{
				this._IsManuscript = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOfItems", DbType="Int")]
	public System.Nullable<int> NumOfItems
	{
		get
		{
			return this._NumOfItems;
		}
		set
		{
			if ((this._NumOfItems != value))
			{
				this._NumOfItems = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOfPages", DbType="Int")]
	public System.Nullable<int> NumOfPages
	{
		get
		{
			return this._NumOfPages;
		}
		set
		{
			if ((this._NumOfPages != value))
			{
				this._NumOfPages = value;
			}
		}
	}
}

public partial class StatisticsSearchResult
{
	
	private int _Customer_Gender;
	
	private int _Period;
	
	private int _Send_Method;
	
	private int _Language;
	
	private int _Search_Type;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	private int _Degree;
	
	private bool _IsBook;
	
	private bool _IsArticle;
	
	private bool _IsThesis;
	
	private bool _IsDocument;
	
	private bool _IsImage;
	
	private bool _IsManuscript;
	
	private System.Nullable<int> _NumOfItems;
	
	private System.Nullable<int> _NumOfPages;
	
	public StatisticsSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Customer_Gender", DbType="Int NOT NULL")]
	public int Customer_Gender
	{
		get
		{
			return this._Customer_Gender;
		}
		set
		{
			if ((this._Customer_Gender != value))
			{
				this._Customer_Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="Int NOT NULL")]
	public int Period
	{
		get
		{
			return this._Period;
		}
		set
		{
			if ((this._Period != value))
			{
				this._Period = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Send_Method", DbType="Int NOT NULL")]
	public int Send_Method
	{
		get
		{
			return this._Send_Method;
		}
		set
		{
			if ((this._Send_Method != value))
			{
				this._Send_Method = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="Int NOT NULL")]
	public int Language
	{
		get
		{
			return this._Language;
		}
		set
		{
			if ((this._Language != value))
			{
				this._Language = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Search_Type", DbType="Int NOT NULL")]
	public int Search_Type
	{
		get
		{
			return this._Search_Type;
		}
		set
		{
			if ((this._Search_Type != value))
			{
				this._Search_Type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Degree", DbType="Int NOT NULL")]
	public int Degree
	{
		get
		{
			return this._Degree;
		}
		set
		{
			if ((this._Degree != value))
			{
				this._Degree = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBook", DbType="Bit NOT NULL")]
	public bool IsBook
	{
		get
		{
			return this._IsBook;
		}
		set
		{
			if ((this._IsBook != value))
			{
				this._IsBook = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsArticle", DbType="Bit NOT NULL")]
	public bool IsArticle
	{
		get
		{
			return this._IsArticle;
		}
		set
		{
			if ((this._IsArticle != value))
			{
				this._IsArticle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsThesis", DbType="Bit NOT NULL")]
	public bool IsThesis
	{
		get
		{
			return this._IsThesis;
		}
		set
		{
			if ((this._IsThesis != value))
			{
				this._IsThesis = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDocument", DbType="Bit NOT NULL")]
	public bool IsDocument
	{
		get
		{
			return this._IsDocument;
		}
		set
		{
			if ((this._IsDocument != value))
			{
				this._IsDocument = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsImage", DbType="Bit NOT NULL")]
	public bool IsImage
	{
		get
		{
			return this._IsImage;
		}
		set
		{
			if ((this._IsImage != value))
			{
				this._IsImage = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsManuscript", DbType="Bit NOT NULL")]
	public bool IsManuscript
	{
		get
		{
			return this._IsManuscript;
		}
		set
		{
			if ((this._IsManuscript != value))
			{
				this._IsManuscript = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOfItems", DbType="Int")]
	public System.Nullable<int> NumOfItems
	{
		get
		{
			return this._NumOfItems;
		}
		set
		{
			if ((this._NumOfItems != value))
			{
				this._NumOfItems = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumOfPages", DbType="Int")]
	public System.Nullable<int> NumOfPages
	{
		get
		{
			return this._NumOfPages;
		}
		set
		{
			if ((this._NumOfPages != value))
			{
				this._NumOfPages = value;
			}
		}
	}
}

public partial class GeneralCollectionAddResult
{
	
	private int _ID;
	
	private string _User_ID;
	
	private System.Nullable<int> _Vistor_ID;
	
	private string _Vistor_Name;
	
	private System.Nullable<int> _Gender;
	
	private System.Nullable<int> _Counter_ID;
	
	private System.Nullable<System.DateTime> _Receive_Date;
	
	private System.Nullable<int> _NoBooks;
	
	private string _MobileNo;
	
	public GeneralCollectionAddResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50)")]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_ID", DbType="Int")]
	public System.Nullable<int> Vistor_ID
	{
		get
		{
			return this._Vistor_ID;
		}
		set
		{
			if ((this._Vistor_ID != value))
			{
				this._Vistor_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_Name", DbType="NVarChar(255)")]
	public string Vistor_Name
	{
		get
		{
			return this._Vistor_Name;
		}
		set
		{
			if ((this._Vistor_Name != value))
			{
				this._Vistor_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
	public System.Nullable<int> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter_ID", DbType="Int")]
	public System.Nullable<int> Counter_ID
	{
		get
		{
			return this._Counter_ID;
		}
		set
		{
			if ((this._Counter_ID != value))
			{
				this._Counter_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receive_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Receive_Date
	{
		get
		{
			return this._Receive_Date;
		}
		set
		{
			if ((this._Receive_Date != value))
			{
				this._Receive_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBooks", DbType="Int")]
	public System.Nullable<int> NoBooks
	{
		get
		{
			return this._NoBooks;
		}
		set
		{
			if ((this._NoBooks != value))
			{
				this._NoBooks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(50)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this._MobileNo = value;
			}
		}
	}
}

public partial class GeneralCollectionSearchResult
{
	
	private int _ID;
	
	private string _User_ID;
	
	private System.Nullable<int> _Vistor_ID;
	
	private string _Vistor_Name;
	
	private System.Nullable<int> _Gender;
	
	private System.Nullable<int> _Counter_ID;
	
	private System.Nullable<System.DateTime> _Receive_Date;
	
	private System.Nullable<int> _NoBooks;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	private string _MobileNo;
	
	public GeneralCollectionSearchResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50)")]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_ID", DbType="Int")]
	public System.Nullable<int> Vistor_ID
	{
		get
		{
			return this._Vistor_ID;
		}
		set
		{
			if ((this._Vistor_ID != value))
			{
				this._Vistor_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_Name", DbType="NVarChar(255)")]
	public string Vistor_Name
	{
		get
		{
			return this._Vistor_Name;
		}
		set
		{
			if ((this._Vistor_Name != value))
			{
				this._Vistor_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
	public System.Nullable<int> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter_ID", DbType="Int")]
	public System.Nullable<int> Counter_ID
	{
		get
		{
			return this._Counter_ID;
		}
		set
		{
			if ((this._Counter_ID != value))
			{
				this._Counter_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receive_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Receive_Date
	{
		get
		{
			return this._Receive_Date;
		}
		set
		{
			if ((this._Receive_Date != value))
			{
				this._Receive_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBooks", DbType="Int")]
	public System.Nullable<int> NoBooks
	{
		get
		{
			return this._NoBooks;
		}
		set
		{
			if ((this._NoBooks != value))
			{
				this._NoBooks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(50)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this._MobileNo = value;
			}
		}
	}
}

public partial class GeneralCollectionEditResult
{
	
	private int _ID;
	
	private string _User_ID;
	
	private System.Nullable<int> _Vistor_ID;
	
	private string _Vistor_Name;
	
	private System.Nullable<int> _Gender;
	
	private System.Nullable<int> _Counter_ID;
	
	private System.Nullable<System.DateTime> _Receive_Date;
	
	private System.Nullable<int> _NoBooks;
	
	private string _MobileNo;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	public GeneralCollectionEditResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50)")]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_ID", DbType="Int")]
	public System.Nullable<int> Vistor_ID
	{
		get
		{
			return this._Vistor_ID;
		}
		set
		{
			if ((this._Vistor_ID != value))
			{
				this._Vistor_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_Name", DbType="NVarChar(255)")]
	public string Vistor_Name
	{
		get
		{
			return this._Vistor_Name;
		}
		set
		{
			if ((this._Vistor_Name != value))
			{
				this._Vistor_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
	public System.Nullable<int> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter_ID", DbType="Int")]
	public System.Nullable<int> Counter_ID
	{
		get
		{
			return this._Counter_ID;
		}
		set
		{
			if ((this._Counter_ID != value))
			{
				this._Counter_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receive_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Receive_Date
	{
		get
		{
			return this._Receive_Date;
		}
		set
		{
			if ((this._Receive_Date != value))
			{
				this._Receive_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBooks", DbType="Int")]
	public System.Nullable<int> NoBooks
	{
		get
		{
			return this._NoBooks;
		}
		set
		{
			if ((this._NoBooks != value))
			{
				this._NoBooks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(50)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this._MobileNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
}

public partial class GeneralCollectionSearchWithUsersResult
{
	
	private int _ID;
	
	private string _User_ID;
	
	private System.Nullable<int> _Vistor_ID;
	
	private string _Vistor_Name;
	
	private System.Nullable<int> _Gender;
	
	private System.Nullable<int> _Counter_ID;
	
	private System.Nullable<System.DateTime> _Receive_Date;
	
	private System.Nullable<int> _NoBooks;
	
	private System.Nullable<System.DateTime> _Creation_Date;
	
	private string _MobileNo;
	
	public GeneralCollectionSearchWithUsersResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50)")]
	public string User_ID
	{
		get
		{
			return this._User_ID;
		}
		set
		{
			if ((this._User_ID != value))
			{
				this._User_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_ID", DbType="Int")]
	public System.Nullable<int> Vistor_ID
	{
		get
		{
			return this._Vistor_ID;
		}
		set
		{
			if ((this._Vistor_ID != value))
			{
				this._Vistor_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vistor_Name", DbType="NVarChar(255)")]
	public string Vistor_Name
	{
		get
		{
			return this._Vistor_Name;
		}
		set
		{
			if ((this._Vistor_Name != value))
			{
				this._Vistor_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
	public System.Nullable<int> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this._Gender = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Counter_ID", DbType="Int")]
	public System.Nullable<int> Counter_ID
	{
		get
		{
			return this._Counter_ID;
		}
		set
		{
			if ((this._Counter_ID != value))
			{
				this._Counter_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Receive_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Receive_Date
	{
		get
		{
			return this._Receive_Date;
		}
		set
		{
			if ((this._Receive_Date != value))
			{
				this._Receive_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoBooks", DbType="Int")]
	public System.Nullable<int> NoBooks
	{
		get
		{
			return this._NoBooks;
		}
		set
		{
			if ((this._NoBooks != value))
			{
				this._NoBooks = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Creation_Date
	{
		get
		{
			return this._Creation_Date;
		}
		set
		{
			if ((this._Creation_Date != value))
			{
				this._Creation_Date = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="NVarChar(50)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this._MobileNo = value;
			}
		}
	}
}
#pragma warning restore 1591
